### PR TITLE
feat: add support for priority matching

### PR DESCRIPTION
**Pull request by shink**
ideas:

- sort the policies by priority value when loading policies
- use binary insertion when adding a policy with priority value

Fix: https://github.com/casbin/jcasbin/issues/173

### CODE REVIEW

**Comment by hsluoyz** [comment]
@shink fix all:

image

**Comment by shink** [comment]
> @shink fix all:
> 
> image

Ok, I will.

**Comment by shy1st** [comment]
@shink I think you should change the commit message to "feat: add support for priority matching", so you can pass the check named "semantic pull request"

**Comment by shink** [comment]
> @shink I think you should change the commit message to "feat: add support for priority matching", so you can pass the check named "semantic pull request"

Thank you! 👍

**Comment by hsluoyz** [comment]
@shink any progress?

**Comment by shink** [comment]
> @shink any progress?

Well, the reason why the test failed is the **NullPointerException**. I will fix them immediately.

**Comment by shink** [comment]
@hsluoyz @shy1st It is necessary to pass the check named "codeclimate"?

**Comment by hsluoyz** [comment]
@mango-6bd plz review.

**Comment by hsluoyz** [comment]
> @hsluoyz @shy1st It is necessary to pass the check named "codeclimate"?

No.

**Review by nodece — APPROVED** [review]
LGTM

**Pull request merged**
