### PR TITLE
fix: priority cannot be non first policy element

### PR DESCRIPTION
**Pull request by shink**
Fix: #177

### CODE REVIEW

**Comment by shink** [comment]
@hsluoyz @shy1st Why has this [task](https://github.com/casbin/jcasbin/actions/runs/771239416) timed out again? Did i do something wrong? :-(

**Comment by hsluoyz** [comment]
@shy1st plz have a look:

image

**Comment by shy1st** [comment]
@hsluoyz @shink I fix this bug.

**Comment by hsluoyz** [comment]
@shy1st how is it fixed?

**Comment by shy1st** [comment]
> @shy1st how is it fixed?

I'm not very clear about the cause,I just tried again.

**Pull request merged**
