### PR TITLE
feat: add string adapter

### PR DESCRIPTION
**Pull request by biswajitpatra**
- [x] Add string adapter 
- [x] Add tests for it

### CODE REVIEW

**Comment by hsluoyz** [comment]
@biswajitpatra fix:

image

**Comment by tangyang9464** [comment]
@biswajitpatra @hsluoyz We should create a new repo for adapter instead of merging it into jcasbin

**Comment by biswajitpatra** [comment]
@tangyang9464 This PR was inspired from [stringAdapter](https://github.com/casbin/node-casbin/blob/master/src/persist/stringAdapter.ts) in [casbin-node](https://github.com/casbin/node-casbin.git).

That's why I tried to add the adapter to this repo itself.

**Comment by hsluoyz** [comment]
@biswajitpatra please make PR to this new repo: https://github.com/jcasbin/string-adapter

**Pull request closed without merging**
