### PR TITLE
add Dispatcher, UpdatableAdapter and DistributedEnforcer 

### PR DESCRIPTION
**Pull request by canxer314**

### CODE REVIEW

**Comment by canxer314** [comment]
I didn't find a good way to split into smaller pr

**Comment by hsluoyz** [comment]
@canxer314 I saw your 3 PRs. Maybe you can propose the 1st PR only, so we can work on it to make it merged. Then you can start the 2nd or 3rd PRs after that. Does it sound make sense?

**Comment by canxer314** [comment]
> @canxer314 I saw your 3 PRs. Maybe you can propose the 1st PR only, so we can work on it to make it merged. Then you can start the 2nd or 3rd PRs after that. Does it sound make sense?

Ok just do as you said

**Comment by hsluoyz** [comment]
@canxer314 BTW, is there a reason for you to contribute jCasbin?

**Comment by canxer314** [comment]
> @canxer314 BTW, is there a reason for you to contribute jCasbin?

I like your great design and my work need it. Besides most feature just only support on golang version by now, and I need a Java version.

**Comment by hsluoyz** [comment]
@canxer314 great to hear it!

**Comment by canxer314** [comment]
@hsluoyz it seems that the codebeat will pending forever😂

**Comment by canxer314** [comment]
@hsluoyz it seems that the codebeat will pending forever😂

**Comment by hsluoyz** [comment]
@canxer314 still the same issue. This PR seems to be too big for me to review :(  Can you only offer 1-2 commits in one PR? Also please use English characters only for other language readers! Thanks.

**Pull request closed without merging**
