### PR TITLE
fix: Make ecforceEx return a entity which carry expain and result

### PR DESCRIPTION
**Pull request by jakiuncle**
[fix] Make ecforceEx return a entity which carry expain and result

### CODE REVIEW

**Comment by jakiuncle** [comment]
@imp2002 plz review

**Review by imp2002 — CHANGES_REQUESTED** [review]
Change enforceExWithMatcher too.

**Comment by imp2002** [comment]
Fix: #304 #305

**Comment by jakiuncle** [comment]
ok, i see you have slove this problem,i close this pr

**Pull request closed without merging**
