### PR TITLE
Porting casbin support for pattern functions in g (1st arg and domain)

### PR DESCRIPTION
**Pull request by cguillot**
This PR is a port of casbin support for pattern functions in g.
Also a few refactoring following sonar advices in BuiltInFunctions.

Waiting for your review,

thanks.

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @cguillot , thanks for this functionality! Please fix the DCO.

@tldyl please review.

**Review by tldyl — APPROVED** [review]
Reviewed.

**Comment by hsluoyz** [comment]
@cguillot I saw a lot of "Merch branch" commits. It seems that you pulled from origin between your commits. Would you mind removing such commits by resetting/rebasing the commits?

**Comment by cguillot** [comment]
Sure @hsluoyz i will handle this, thank you, and sorry for the mess!

**Comment by cguillot** [comment]
Hi,
I have resetted my commits, seems more clear...
Still some codebeat info issues, do i try to propose a fix ?
Thanks.

**Comment by hsluoyz** [comment]
@cguillot lgtm!

**Comment by hsluoyz** [comment]
@tldyl please make a new release.

**Pull request merged**
