### PR TITLE
fix: remove multiple domains in gFunction and simplify cache

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>

### CODE REVIEW

**Comment by hmemcpy** [comment]
Hi, sorry for bumping a closed PR, but since upgrading to this version this morning (from 1.22.3, we've started getting random `false` values from the enforcer. I haven't yet investigated the root cause, but reverting back to 1.22.3 stopped those issues.

Not sure what might have gone wrong...

**Comment by hmemcpy** [comment]
Logs had a whole lot of `com.googlecode.aviator.exception.ExpressionRuntimeException: <Nil, null> is not a boolean value` btw... I'm trying to create a repro for this.

**Comment by hsluoyz** [comment]
@tangyang9464

**Comment by tangyang9464** [comment]
> Logs had a whole lot of `com.googlecode.aviator.exception.ExpressionRuntimeException: <Nil, null> is not a boolean value` btw... I'm trying to create a repro for this.

@hmemcpy Could you provide more information such as the call stack to solve the problem?

**Comment by hsluoyz** [comment]
@damienmiheev plz create new issue

**Comment by damienmiheev** [comment]
@hsluoyz 
sorry, there is already one: https://github.com/casbin/jcasbin/issues/292
i've just found that first time this issue was mentioned here, so that's why i left this comment

**Pull request merged**
