### PR TITLE
docs: Add github action badge.

### PR DESCRIPTION
**Pull request by shy1st**
Fix: #156

### CODE REVIEW

**Comment by shy1st** [comment]
the change of hibernate-adapter: https://github.com/jcasbin/hibernate-adapter/pull/9

**Comment by hsluoyz** [comment]
Fix:

image

**Comment by shy1st** [comment]
@hsluoyz If I fix the semantic pull request, it will semantic release when meger this pr.

**Comment by hsluoyz** [comment]
@shy1st then use another prefix that doesn't trigger release (like chore? I don't know the specific term, but there must be one)

**Comment by shy1st** [comment]
@hsluoyz The workflow name of github action is unreasonable, which cause the badge cannot be displayed.Now I have fixed it.

**Comment by hsluoyz** [comment]
@shy1st it's still not right. You can make sure the badge looks good before making the PR ready.

image

**Comment by shy1st** [comment]
@hsluoyz It is right.When merging this pr, it will rebuild.After the rebuild it will display normal.

**Comment by hsluoyz** [comment]
@shy1st great, thanks!

**Pull request merged**
