### PR TITLE
fix: Implemented arrayRemoveDuplicates

### PR DESCRIPTION
**Pull request by rob-3r7o**
fix: Implemented a method which returned "true" without doing anything, used in Policy.java class

### CODE REVIEW

**Comment by rob-3r7o** [comment]
I added "fix" in title and comment section, but still getting "Semantic Pull Request" error

**Comment by tangyang9464** [comment]
> I added "fix" in title and comment section, but still getting "Semantic Pull Request" error

@rob-3r7o Commit instead of comment. Just use ``git`` to modify commit message.

**Comment by hsluoyz** [comment]
@rob-3r7o plz DON'T close this PR again.

**Review by tangyang9464 — APPROVED** [review]
LGTM

**Pull request merged**
