### PR TITLE
Add validation on param size for enforce method

### LINKED ISSUE #33: suggestion: allow to query enforcer for number of expected parameters for enforce call
Given the different styles of supported models and the fact that the data source might be unknown/out of our control it would be useful to be able to determine the number of parameters required for a call to `enforcer#enforce(...)#. 

Or at least fail with something better than `Method threw 'java.lang.ArrayIndexOutOfBoundsException' exception.`

e.g.

```java
enforcer.enforce("alice","data1","read")
```
would thrown an exception for

```
p, admin, domain1, data1, read
p, admin, domain1, data1, write
p, admin, domain2, data2, read
p, admin, domain2, data2, write

g, alice, admin, domain1
g, bob, admin, domain2
```
but would succeed for
```
p, alice, data1, read
p, bob, data2, write
p, data_group_admin, data_group, write

g, alice, data_group_admin
g2, data1, data_group
g2, data2, data_group
```

I thought I could guess it from `enforcer.getAllActions()` but in the 1st case this returns 
`actions:[data1, data1, data2, data2]`
while in the 2nd it (correctly) returns
`actions:[read, write, write]`

I think this particular scenario would be solvable with `enforcer.getAllDomains()` but is not very scalable as a solution for future changes.

### PR DESCRIPTION
**Pull request by DemianTinkiel**
fixes #33

### CODE REVIEW

**Comment by hsluoyz** [comment]
Hi @DemianTinkiel , I think the ``validateEnforceSection()`` may cause too much overhead in ``enforce()``. I prefer to move it to a separate function like ``validateEnforce()`` which is just besides ``enforce()``. So anyone who is not sure about the input can call it like:

```java
try {
  enforcer.validateEnforce("alice", "data1", "read");
} catch ...

enforcer.enforce("alice", "data1", "read");
```

**Comment by DemianTinkiel** [comment]
ok @hsluoyz . I assume it goes in CoreEnforcer? ie for all APIs or is it specific to RBAC?

**Comment by DemianTinkiel** [comment]
@hsluoyz am I correct to assume `org.casbin.jcasbin.util.Util#logPrint` is the official way to log stuff? if so it seems a bit limited:

1. Always at INFO level
2. Logger.getLogger does not allow for simple use of log implementations. SLF4J would be best as it would still work as is now but also allow to use logback etc

**Comment by hsluoyz** [comment]
> I assume it goes in CoreEnforcer? ie for all APIs or is it specific to RBAC?

I think ``CoreEnforcer`` is OK.

**Comment by hsluoyz** [comment]
> am I correct to assume org.casbin.jcasbin.util.Util#logPrint is the official way to log stuff? if so it seems a bit limited:

I think we can change it to SLF4J. Can you help implement it in another PR?

**Comment by DemianTinkiel** [comment]
> I think we can change it to SLF4J. Can you help implement it in another PR?
Sure. I'll do that. I assume you still want all logs coming as `org.casbin.jcasbin` regardless of what class outputs them (as in opposed to e.g. `org.casbin.jcasbin.main.CoreEnforcer`)? If so Util would need logWarn and logErr or similar methods

**Comment by hsluoyz** [comment]
> Sure. I'll do that. I assume you still want all logs coming as org.casbin.jcasbin regardless of what class outputs them (as in opposed to e.g. org.casbin.jcasbin.main.CoreEnforcer)?

Yes. I think ``org.casbin.jcasbin`` would be enough for now.

**Pull request merged**
