### PR TITLE
Use codocov instead of coverall.

### PR DESCRIPTION
**Pull request by shy1st**

### CODE REVIEW

**Comment by shy1st** [comment]
@hsluoyz Can we use codecov instead of coverage? Maybe coverage combined with the maven plugin is not  supported with Github Actions at present.
please see: https://github.com/cucumber/cucumber-jvm/pull/2162

**Comment by hsluoyz** [comment]
@shy1st sure, I don't have any preference on code coverage tool. Actually maybe `codecov` is more popular.

**Comment by hsluoyz** [comment]
@shy1st plz also update the badge:

image

**Pull request merged**
