### PR TITLE
fix: FilteredAdapter cast is correctly casting to interface now

### PR DESCRIPTION
**Pull request by doodleincode**
Fix: https://github.com/casbin/jcasbin/issues/154

### CODE REVIEW

**Comment by hsluoyz** [comment]
@doodleincode plz fix:

image

**Comment by hsluoyz** [comment]
I think this PR may also fix an old issue: https://github.com/casbin/jcasbin/issues/128#issuecomment-771403546

@shreyasGit can you verify it?

**Comment by shy1st** [comment]
Owing to the fact that we replaced travis with gitHub action  recently, yesterday I found there is still problem with own github action:the coverall_token can not be readed when we commit a pr, which can cause own github action work fail.Recently,So at present, GitHub action work fail is not your reason. @doodleincode  Recently I have been trying to fix this problem. I'm sorry for the inconvenience.

**Comment by doodleincode** [comment]
Branch got a little wonky with the amended commit message, but I think it's ok now. @hsluoyz, other than the CI failing, it looks like the other checks are passing.

**Comment by hsluoyz** [comment]
Well, I think our CI is broken for now. @shy1st can you manually check if this PR works good for all our tests?

**Review by shy1st — APPROVED** [review]
I think it is no problem.

**Comment by hsluoyz** [comment]
@shy1st plz release on Maven and GitHub.

**Pull request merged**
