### PR TITLE
feat: use janino instead of bsh.

### PR DESCRIPTION
**Pull request by shy1st**
Fix: #146

### CODE REVIEW

**Comment by shy1st** [comment]
Why travis ci doesn't work?

**Comment by hsluoyz** [comment]
@The28AWG please review.

**Comment by hsluoyz** [comment]
@shy1st plz fix conflicts.

**Comment by hsluoyz** [comment]
@shy1st next time plz wait for PR review.

Also check out why Maven is not auto-released: https://mvnrepository.com/artifact/org.casbin/jcasbin

**Pull request merged**
