### PR TITLE
fix: use github action rather than travis.

### PR DESCRIPTION
**Pull request by shy1st**

### CODE REVIEW

**Comment by hsluoyz** [comment]
@shy1st fix:

image

**Comment by shy1st** [comment]
@hsluoyz I don't think this PR is necessary to sematic release, so the error of Semantic Pull Request I will not fix.

**Comment by hsluoyz** [comment]
> I don't think this PR is necessary to sematic release, so the error of Semantic Pull Request I will not fix.

It can start with "fix: xxx"

> In addition, please do not merge for the time being, work has not finished.

If it's not ready, plz set it to "Draft"

**Comment by hsluoyz** [comment]
@shy1st plz fix conflicts.

**Comment by shy1st** [comment]
I think now we can merge this pr.

**Comment by hsluoyz** [comment]
@shy1st the new build after this PR failed: https://github.com/casbin/jcasbin/runs/1985409384?check_suite_focus=true

**Pull request merged**
