### PR TITLE
fix: CustomFunction.replaceTargets replaces too much

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>

fix: #209

### CODE REVIEW

**Comment by tangyang9464** [comment]
@rob-spoor @hsluoyz

**Comment by rob-spoor** [comment]
@tangyang9464 that fix still can lead to replacing too much. Consider the following keys:
* r_value
* r_customer

The `replaceFirst` call for `r_value` results in `r.value`. If the expression is `r.customer.value`, replacing `r.value` with `r_value` results in `r.customer_value`.
The `replaceFirst` call for `r_customer` results in `r.customer`. Replacing `r.customer` with `r_customer` in the intermediate result `r.customer_value` results in `r_customer_value`. This is the same behaviour as I reported in #209.

**Comment by hsluoyz** [comment]
@rob-spoor

**Comment by tangyang9464** [comment]
@rob-spoor plz check again,the idea refer to [casbin-EscapeAssertion](https://github.com/casbin/casbin/blob/e5ea4ae5631bf10108704374bd2e5a8bb92740ed/util/util.go#L26-L36)

**Comment by rob-spoor** [comment]
If I compare that regex, I see some differences:
* `!` is present in the Go code but not in this PR (between `-` and `*`).
* The Go code doesn't include the `[0-9]*` part. However, I can see that this is for properties like `r2` and `p2`.
* The replacing is done differently. This does look correct - the entire match is the same as `$1$2` followed by `.`, so the replacing effectively does the same (replace the first dot at the end of the regex with an underscore).

I think that if the `!` is added the effect will be identical.

**Comment by tangyang9464** [comment]
@rob-spoor
1. have added ``!``
2. this feture ``[0-9]*`` have a PR  [#833](https://github.com/casbin/casbin/pull/833#issuecomment-878688883) open,it just not merged yet

**Comment by rob-spoor** [comment]
@tangyang9464 always good to plan ahead 😄

**Comment by tangyang9464** [comment]
> @tangyang9464 always good to plan ahead 😄

Thanks for helping to find the bug

**Comment by rob-spoor** [comment]
You're welcome.

**Comment by tangyang9464** [comment]
@hsluoyz plz review

**Pull request merged**
